name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install node modules
      run: npm install
    - name: Manually change the config file
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Start the Backend
      run: npm run start-be & 
    - name: Start the Frontend
      run: npm run start-fe &
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Playwright UI tests
      run: npm run test

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.BE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
  deploy-fe:
    needs: deploy-be
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.FE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true